"""Add diagnostic orchestration sessions table

Revision ID: add_orchestration
Revises: d632f34f168e
Create Date: 2025-08-08 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_orchestration'
down_revision = 'd632f34f168e'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostic_orchestration_sessions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.String(length=255), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('vehicle_id', sa.Integer(), nullable=True),
        sa.Column('current_state', sa.String(length=50), nullable=True),
        sa.Column('vehicle_snapshot', sa.JSON(), nullable=True),
        sa.Column('live_telemetry', sa.JSON(), nullable=True),
        sa.Column('hypotheses', sa.JSON(), nullable=True),
        sa.Column('execution_history', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['vehicle_id'], ['user_vehicles.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostic_orchestration_sessions_id'), 'diagnostic_orchestration_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_diagnostic_orchestration_sessions_session_id'), 'diagnostic_orchestration_sessions', ['session_id'], unique=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnostic_orchestration_sessions_session_id'), table_name='diagnostic_orchestration_sessions')
    op.drop_index(op.f('ix_diagnostic_orchestration_sessions_id'), table_name='diagnostic_orchestration_sessions')
    op.drop_table('diagnostic_orchestration_sessions')
    # ### end Alembic commands ###